services:
  oidcvpn:
    image: danmorrison/oidcvpn
    build:
      context: .
      dockerfile: Dockerfile
    # The oidc plugin only compiles under x64 currently
    platform: linux/amd64
    container_name: openvpn
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - OIDCVPN_S3_URI
      - OIDCVPN_OIDC_CLIENT_ID
      - OIDCVPN_OIDC_CLIENT_SECRET
      - OIDCVPN_OIDC_ISSUER
      - OIDCVPN_OI
      - DC_REDIRECT_URI
      - OIDCVPN_OIDC_EXTRA_SCOPES
      - OIDCVPN_OIDC_USER_NAME_FIELD
    ports:
      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
